name: Create and Store Kubeconfig

on:
  workflow_dispatch:

 inputs:
      secname:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Secret name'
        # Default value if no value is explicitly provided
        default: 'testing
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string
        

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create kubeconfig
      run: |
        ls -ltra 

        

    - name: Store kubeconfig as secret
      run: |
        aws secretsmanager create-secret --name ${{ inputs.secname }} \
          --description "bom file" \
          --secret-string file://bom
